package co.unicauca.restaurante.cliente.presentation;
import co.unicauca.restaurante.cliente.acces.IComponenteAccess;
import co.unicauca.restaurante.cliente.acces.Factory;
import static co.unicauca.restaurante.cliente.infra.Messages.successMessage;
import co.unicauca.restaurante.cliente.domain.services.ComponenteService;
import co.unicauca.restaurante.comunicacion.domain.Componente;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Usuario
 */
public class GUIaddComponenteViewController extends javax.swing.JFrame {

    /** Creates new form GUIaddComponenteViewController */
    String ruta = null;
    public GUIaddComponenteViewController() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_ImagenComponente = new javax.swing.JLabel();
        btn_ImagenComponente = new javax.swing.JButton();
        btn_EditPlato = new javax.swing.JButton();
        btn_SalirComp = new javax.swing.JButton();
        txt_ComponenteID = new javax.swing.JTextField();
        txt_CompnenteNombre = new javax.swing.JTextField();
        txt_CompPrecio = new javax.swing.JTextField();
        txt_ComponenteTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Componente");

        jLabel2.setText("ID:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Precio:");

        lbl_ImagenComponente.setBackground(new java.awt.Color(0, 0, 0));
        lbl_ImagenComponente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_ImagenComponente.setText("Elegir Imagen");
        btn_ImagenComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImagenComponenteActionPerformed(evt);
            }
        });

        btn_EditPlato.setText("Agregar");
        btn_EditPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditPlatoActionPerformed(evt);
            }
        });

        btn_SalirComp.setText("Salir");
        btn_SalirComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirCompActionPerformed(evt);
            }
        });

        txt_CompnenteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CompnenteNombreActionPerformed(evt);
            }
        });

        txt_ComponenteTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ComponenteTipoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(33, 33, 33)
                                .add(jLabel1))
                            .add(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(txt_ComponenteID, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .add(txt_CompnenteNombre)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txt_CompPrecio)
                                    .add(txt_ComponenteTipo))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(66, 66, 66)
                                        .add(lbl_ImagenComponente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn_ImagenComponente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(28, 28, 28))))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(73, 73, 73)
                        .add(btn_EditPlato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(29, 29, 29)
                        .add(btn_SalirComp)))
                .add(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(37, 37, 37)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(txt_ComponenteID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel2))
                                .add(30, 30, 30))
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel3)
                                .add(txt_CompnenteNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txt_ComponenteTipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txt_CompPrecio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))
                        .add(89, 89, 89)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btn_EditPlato)
                            .add(btn_SalirComp))
                        .add(28, 28, 28))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lbl_ImagenComponente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btn_ImagenComponente)
                        .addContainerGap(106, Short.MAX_VALUE))))
        );

        btn_EditPlato.getAccessibleContext().setAccessibleDescription("");
        btn_EditPlato.getAccessibleContext().setAccessibleParent(jLabel4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ImagenComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImagenComponenteActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser();
        int ap= j.showOpenDialog(this);
        if(ap == JFileChooser.APPROVE_OPTION){
            ruta=j.getSelectedFile().getAbsolutePath();
        }
    }//GEN-LAST:event_btn_ImagenComponenteActionPerformed

    private void btn_EditPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditPlatoActionPerformed
        IComponenteAccess service = Factory.getInstance().getComponenteService();
        // Inyecta la dependencia
        ComponenteService compService = new ComponenteService(service);

        Componente comp = new Componente();
        comp.setCompId(Integer.parseInt(txt_ComponenteID.getText()));
        comp.setCompNombre(txt_CompnenteNombre.getText());
        comp.setTipo(txt_ComponenteTipo.getText());
        comp.setPrecio(Integer.parseInt(txt_CompPrecio.getText()));
        //comp.setCompImage(Byte.valueOf(lbl_ImagenComponente.getText()));

        try {
            Boolean response = compService.update(comp);
            if(response==true){
                successMessage("Componente fue Agregado con éxito.", "Atención");
                clearControls();
                btn_EditPlato.setVisible(false);
            }else{
                successMessage("Ocurrio un error al Agregar el componente.", "Atención");
                clearControls();
                btn_EditPlato.setVisible(false);
            }

        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
    }//GEN-LAST:event_btn_EditPlatoActionPerformed
public void clearControls() {
        txt_ComponenteID.setText("");
        txt_CompnenteNombre.setText("");
        txt_CompPrecio.setText("");
        lbl_ImagenComponente.setText("");       
    }
    private void btn_SalirCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirCompActionPerformed
        // TODO add your handling code here: Boton salir
        System.exit(0);
    }//GEN-LAST:event_btn_SalirCompActionPerformed

    private void txt_CompnenteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CompnenteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CompnenteNombreActionPerformed

    private void txt_ComponenteTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ComponenteTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ComponenteTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIaddComponenteViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIaddComponenteViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIaddComponenteViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIaddComponenteViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIaddComponenteViewController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EditPlato;
    private javax.swing.JButton btn_ImagenComponente;
    private javax.swing.JButton btn_SalirComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ImagenComponente;
    private javax.swing.JTextField txt_CompPrecio;
    private javax.swing.JTextField txt_CompnenteNombre;
    private javax.swing.JTextField txt_ComponenteID;
    private javax.swing.JTextField txt_ComponenteTipo;
    // End of variables declaration//GEN-END:variables

}
